[build-system]
requires = [
    "wheel",
    "setuptools>=68.0",
]
build-backend = "setuptools.build_meta"

[project]
version = "0.1.0"
name = "overflow-labs"
description = "A Study of How Developer Behavior Shifted in the Generative-AI Era"
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "Aditya Patil" },
    { name = "Tomasz Soróbka" },
    { name = "Roham Koohestani" },
]
dependencies = [
    "lxml>=5.2",
    "torch>=2.4",
    "numpy>=1.26",
    "pandas>=2.2",
    "scipy>=1.13",
    "duckdb>=1.1",
    "py7zr>=0.22",
    "pyyaml>=6.0",
    "xgboost>=2.1",
    "seaborn>=0.13",
    "pyarrow>=17.0",
    "bertopic>=0.16",
    "matplotlib>=3.9",
    "accelerate>=0.34",
    "statsmodels>=0.14",
    "scikit-learn>=1.5",
    "transformers>=4.44",
    "python-dotenv>=1.0",
    "beautifulsoup4>=4.12",
    "huggingface_hub>=0.25",
    "sentence-transformers>=3.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.3",
    "jupyter>=1.0",
    "ipykernel>=6.29",
    "pytest-cov>=5.0",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["source*"]

[tool.pytest.ini_options]
python_files = ["test_*.py"]
testpaths = ["tests"]